18F/identity-dashboard

app/assets/stylesheets/components/_button.scss
app/controllers/users/applications_controller.rb
app/views/users/applications/_form.html.slim
app/views/users/applications/edit.html.slim
app/views/users/applications/index.html.slim
app/views/users/applications/show.html.slim
db/schema.rb

Rationale:
Service providers may want to register applications, and then toggle them on/off.

add applications.active boolean flag

---

Gemfile
Gemfile.lock
app/mailers/user_mailer.rb
spec/mailers/user_mailer_spec.rb
spec/requests/applications_spec.rb

Fixes bug in email subject where I18n key was wrong, and adds tests to verify.

fix email subject for application create/approve notifications

---

config/initializers/secure_headers.rb

Equivalent to what the -idp app does for all service providers.

Whitelist all IdP domains for Content Security Policy

---

config/secrets.yml

**Why**:
I thought default was shared across all environments, it is shared
across all enviromments _except_ production, so this brings back
the secrets I removed from prod accidentally in 4d7a70f9498367

Fix production secrets

---

config/deploy.rb

**Why**:
nginx runs processes as the "nobody" user so files need to be world-readable
in order to be served by nginx

Make deploy.json world-readable

---

config/deploy.rb

(it's a bummer this worked fine in 18F/identity-idp and didn't need this require. I tested this one manually)
**Why**:
Because I got this error when I deployed:
```
NoMethodError: undefined method `to_json' for #<Hash:0x007fd504082470>
Did you mean?  to_s
```

Add missing require

---

app/services/deploy_status_checker.rb

**Why**:
Matches our deploy flow: dev -> qa -> demo

Rearrange order of environments on deploy dashboard

---

config/secrets.yml

**why**
otherwise, it overwrites secret key base for sp-rails or sp-sinatra because they shared the same env var name.

change secret_key_base to dashboard_secret_key_base

---

app/services/deploy_status_checker.rb

When checking the deploy status on our applications, we must
open an HTTP connection to the API; when the service is completely
down, the Rack::Timeout is reached before the individual API calls
time out.
Add an open_timeout to the HTTP request to each individual API.

Adds 2 second open_timeout to HTTP request

---

.rubocop.yml
Gemfile
Gemfile.lock
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/sessions_controller.rb
app/models/user.rb
config/locales/en.yml
db/migrate/20160715161608_uui_dto_string.rb
db/schema.rb
lib/saml_config.rb
spec/requests/slo_spec.rb
spec/support/fake_saml_idp.rb

**Why**:
Better UX, since we end up on dashboard site, where user
clicked the Sign Out button.

SP-initiated logout

---

.travis.yml
Gemfile
Gemfile.lock
app/controllers/api/service_providers_controller.rb
app/serializers/service_provider_serializer.rb
bin/setup
config/routes.rb
lib/tasks/dev.rake
spec/controllers/api/service_providers_controller_spec.rb
spec/support/controller_helper.rb

**Why**: Allows active, approved Service Providers to be published
for consumption by identity-idp

Add /api/service_providers endpoint

---

.env.test
Gemfile
Gemfile.lock
app/controllers/api/service_providers_controller.rb
app/services/service_provider_updater.rb
app/views/layouts/application.html.slim
app/views/users/service_providers/index.html.slim
config/locales/en.yml
config/routes.rb
spec/controllers/api/service_providers_controller_spec.rb
spec/services/service_provider_updater.rb
spec/support/fake_saml_idp.rb

**Why**: Allow self-service one click to publish active SPs to IdP.

Add API endpoint to publish Service Providers

---

app/controllers/users/service_providers_controller.rb
app/models/service_provider.rb

**Why**: Since we're iterating on issuer formats (currently favoring an
URN), remove "issuer" as the ID in routing to avoid illegal URL
characters and broken routes.

Fix broken SP routes

---

README.md
config/saml.yml

**Why**: The `saml.yml` config was missing SSO and SLO URLs, making it
confusing for newcomers (:hand:) as to why auth was broken when cloning
and running locally. Also cleans up and adds a bit of clarity to the
README.

Make running locally easier

---

app/controllers/users/service_providers_controller.rb
app/views/users/service_providers/index.html.slim
spec/features/service_providers_spec.rb

**Why**: As an admin, I want to see all registered agency SPs,
including the ones I’ve created, so that I can easily view and manage
them on behalf of the agency.

Show all SPs to admins

---

app/controllers/api/service_providers_controller.rb
app/serializers/service_provider_serializer.rb
spec/controllers/api/service_providers_controller_spec.rb

**Why**: Active flag filter prevents IdP from removing de-activated
SPs from the IdP cache.
**How**: Let the IdP do its own filtering, by
including the active flag as an attribute in feed.

Include all ServiceProviders in feed

---

Capfile
config/deploy.rb
config/deploy/demo.rb
config/deploy/dev.rb
config/deploy/int.rb
config/deploy/qa.rb
config/deploy/tf.rb

Why
To permit developers to deploy via capistrano
How
Enable SSH proxy (bastion) host

Adds support for bastion host

---

config/deploy.rb

Linking the `bin` folder was not permitting the included binaries to run, which was blocking Tom's console access. Now, you can easily launch a rails console with `bin/rails c` on our remote hosts.

Removes bin from linked directories

---

.rubocop.yml
app/controllers/api/service_providers_controller.rb
app/controllers/users/omniauth_callbacks_controller.rb
app/controllers/users/service_providers_controller.rb
app/controllers/users/sessions_controller.rb
app/mailers/user_mailer.rb
app/serializers/service_provider_serializer.rb
app/services/deploy_status_checker.rb
lib/saml_config.rb
spec/support/fake_saml_idp.rb

**Why**: It's stylish and how we write ruby in the idp app

Enforce trailing comma via rubocop

---

app/controllers/api/service_providers_controller.rb
app/controllers/application_controller.rb
app/controllers/authenticated_controller.rb

**Why**: We do not need this because users can auth with Login.gov

Remove `FORCE_USER` references

---

.travis.yml
spec/rails_helper.rb
spec/spec_helper.rb

**Why**:
* When running `rpsec spec/ --profile`, i18n-tasks was slowest file
* Ran 3 times, each time file took ~2 seconds to run
* Upon investigation, this appears to relate to Simplecov
* See https://github.com/glebm/i18n-tasks/issues/221
* Also https://github.com/colszowka/simplecov/issues/404
* Since there is no proposed solution at the moment (slowness appears to
be coming from `Coverage`, which is part of the Ruby stdlib), the
short term solution is to only run Simplecov on Travis, where required
* New timing for i18n-tasks: under .2 seconds!!!
Before:
```
Top 10 slowest example groups:
I18n
1.8 seconds average (3.59 seconds / 2 examples) ./spec/i18n_spec.rb:4
Users::ServiceProviders
0.17479 seconds average (1.22 seconds / 7 examples) ./spec/requests/service_providers_spec.rb:3
``` …

Only run simplecov in CI env

---

app/models/user.rb
app/views/user_groups/_form.html.slim
spec/features/user_groups_spec.rb

**Why**: Users can only belong to one user group. If we add them to a
second one, that will automatically un-assign them from their first user
group, which is unexpected. More expected to just not show them as an
option. Also will have side benefit of making list of possible users
shorter.

Do not show users who are already in user groups in form

---

app/models/user.rb
app/views/user_groups/_form.html.slim
spec/features/user_groups_spec.rb
spec/models/user_spec.rb

* There was a bug where we were showing only users without a user group
* This lead to an issue where users in a user group were not showing
when editing that user group, leading to them being unassigned
* Now this is fixed and I added a regression test

Show users who are already in a user group when editing

---

app/services/deploy_status_checker.rb
app/views/home/_deploy.html.erb
spec/services/deploy_status_checker_spec.rb

🎉 
We can disable the checks for things like SPs in production by removing the URLs and they'll appear grayed out, I'm not sure what apps exist in which environments.

Show more environments

---

app/controllers/service_providers_controller.rb
app/helpers/service_provider_helper.rb
app/views/service_providers/_form.html.slim
app/views/service_providers/show.html.slim
config/i18n-tasks.yml
config/initializers/simple_form.rb
config/locales/simple_form.en.yml
db/migrate/20170330181317_add_logo_to_service_providers.rb
db/schema.rb
spec/features/service_providers_spec.rb
spec/helpers/service_provider_helper_spec.rb

**WHY**: Agencies can add logos!
When logo name is invalid:
When logo name is valid:

Add ability to set logo name when adding SP

---

app/controllers/service_providers_controller.rb
app/models/service_provider.rb
app/views/service_providers/_form.html.slim
app/views/service_providers/show.html.slim
config/locales/simple_form.en.yml
db/migrate/20170509155224_add_auth_types_to_service_providers.rb
db/schema.rb
spec/features/service_providers_spec.rb

Allows users to set SAML or OpenId Connect
Will change which fields are shown in future PR

Added select for identity protocol to service providers

---

app/assets/javascripts/app/service-provider-form.js
app/views/service_providers/_form.html.slim
app/views/service_providers/edit.html.slim
app/views/service_providers/new.html.slim
spec/features/service_providers_spec.rb

**Why**
Users were filling out unneccessary fields when creating sp's
This eliminates confusion by hiding those fields

Show appropriate fields based on id protocol

---

app/views/service_providers/_form.html.slim
app/views/service_providers/new.html.slim

**Why**
Users who clicked the documentation link
would be directed away from the form
Also added documentation link to the form partial.
Link shows on edit and new forms now.

Changed documentation link on SP form to open in a new tab

---

app/assets/stylesheets/components/_alert.scss
app/controllers/api/service_providers_controller.rb
app/controllers/service_providers_controller.rb
app/services/service_provider_updater.rb
app/views/service_providers/index.html.slim
spec/features/service_providers_spec.rb
spec/services/service_provider_updater_spec.rb

**Why**
Streamlines the process and eliminates an uneccesary extra step

Automatically publish service providers upon save or update

---

Gemfile
Gemfile.lock

__Why__
* The older version is causing builds to fail.
```
Downloading foreman-0.83.0 revealed dependencies not in the API or the lockfile (thor (~> 0.19.1)).
Either installing with `--full-index` or running `bundle update foreman` should fix the problem.
```
__How__
* Update foreman as the error message suggests.

Remove foreman from Gemfile

---

app/controllers/service_providers_controller.rb
app/inputs/json_input.rb
app/serializers/service_provider_serializer.rb
app/views/service_providers/_form.html.slim
app/views/service_providers/show.html.slim
config/locales/simple_form.en.yml
db/migrate/20170531194154_add_multiple_redirect_uris.rb
db/schema.rb
spec/features/service_providers_spec.rb
spec/serializers/service_provider_serializer_spec.rb

**Why**: Better OIDC support
First step of multiple, eventually will follow up with a PR to drop the old column once we have everything running off the new column

Support multiple redirect_uri values

---

Gemfile
Gemfile.lock
Procfile

**Why**: It looks like this was copied and pasted from the IdP code.
The dashboard app uses the IdP app for logins and account creation.
It doesn't send emails itself, so there's no need for Mailcatcher.

Remove unused Mailcatcher gem

---

app/views/home/_deploy.html.erb
config/locales/en.yml

**Why**: timestamp is for chef run, not deploy

Update deploy text

---

app/serializers/service_provider_serializer.rb
db/migrate/20171016184947_drop_redirect_uri_from_service_providers.rb
db/schema.rb
spec/serializers/service_provider_serializer_spec.rb

**Why**: We have fully migrated to the plural redirect_uris column

Cleanup: remove old singular redirect_uri column

---

app/models/service_provider.rb
spec/features/service_providers_spec.rb
spec/models/service_provider_spec.rb

**Why**: We added this validation to the IDP. This means that we need a
corresponding validation on the dashboard since the IDP reads redirect
URIs from the dashboard
This change also includes some code to change the process for adding
multiple URIs so that empty strings don't get added.

Validate that SP redirect uris are parsable uris

---

app/assets/javascripts/app/service-provider-form.js
app/views/service_providers/_form.html.erb
app/views/service_providers/edit.html.erb
app/views/service_providers/new.html.erb

**Why**: The current UI only shows one redirect URI field, so this adds a button to append more.

Provide more redirect URI fields in SP form

---

config/initializers/devise.rb

**Why**: Currently, the timeout is 30 min, which is too short for our
agency developer workflows. This increases to 8 hours, so that a
developer should only have to log in to the dashboard once per day.

Increase the timeout length

---

Gemfile
Gemfile.lock
bin/delayed_job
config/application.rb
spec/controllers/api/service_providers_controller_spec.rb

**Why**: It's not used by the app

Remove delayed_job

---

Procfile

As part of #167, remove the worker process, as the DJ tasks no longer exist.
Tested that `make run` works locally now, and there are no spec failures.

Remove worker process, as Delayed::Job is no longer used

---

app/models/service_provider.rb

**Why**:
We want to share the subject of the piv/cac certificate
with SPs that have a need to know.
**How**:
We add attributes for the subject and presence of the
piv/cac during the login session.

Add piv/cac attributes for OIDC

---

app/views/service_providers/_form.html.erb

This pluralizes a word and adds a `that` to make it more clear.

Fix grammar typo on app update form

---

app/models/service_provider.rb
config/locales/activerecord.en.yml
spec/models/service_provider_spec.rb

**Why**: To streamline agency integration and automate troubleshooting
**How**: Add a model validation to load the certificate with OpenSSL::X509 and return an error if OpenSSL raises an exception

LG-276 Disallow agencies from adding invalid certs into the dashboard

---

app/controllers/service_providers_controller.rb
app/models/service_provider.rb
app/serializers/service_provider_serializer.rb
app/views/service_providers/_form.html.erb
app/views/service_providers/all.html.erb
app/views/service_providers/index.html.erb
app/views/service_providers/show.html.erb
config/locales/simple_form.en.yml
db/migrate/20190320210340_add_ial_to_service_providers.rb
db/schema.rb
spec/factories/service_providers.rb

This is a dependency for https://github.com/18F/identity-idp/pull/2672
The IDP will soon start enforcing validation such that IAL1 service
providers can only request IAL1 attributes, not sensitive attributes.
By default the IDP will consider service providers to be at IAL1. So in
order to avoid any service providers that are relying upon IAL2/LOA3
data, we have to add a corresponding attribute to service providers in
the dashboard.

Add IAL attribute to service providers.

---

app/controllers/service_providers_controller.rb
app/models/service_provider.rb
app/serializers/service_provider_serializer.rb
app/views/service_providers/_form.html.erb
app/views/service_providers/all.html.erb
app/views/service_providers/index.html.erb
app/views/service_providers/show.html.erb
config/locales/simple_form.en.yml
db/migrate/20190320210340_add_ial_to_service_providers.rb
db/schema.rb

* Add IAL attribute to service providers.
This is a dependency for https://github.com/18F/identity-idp/pull/2672
The IDP will soon start enforcing validation such that IAL1 service
providers can only request IAL1 attributes, not sensitive attributes.
By default the IDP will consider service providers to be at IAL1. So in
order to avoid any service providers that are relying upon IAL2/LOA3
data, we have to add a corresponding attribute to service providers in
the dashboard.

Deploy code on 01/21/2019 to int

---

app/views/service_providers/_form.html.erb

All of the form fields in the edit form ought to default to the current
values from the object. That way if a user hits edit, makes no changes,
and hits change, the saved object will be unchanged.
This fixes a bug that would have led to unexpected IAL changes when
users edited service providers.

Set default for IAL input to current value.

---

app/views/users/none.html.erb

We had someone write in about trying to develop against Login and having created an account but not being found, so they saw this error message. They then wrote hello@login.gov to ask about why, and then that help desk directed them to partners@login.gov, which they then emailed.
This helps people in that situation short-circuit that process. Since it's only shown once folks are logged into the dashboard, it seems unlikely to create a significant risk of spam, or of non-developers using it for non-related support questions.

Give the contact email directly for non-found users

---

app/views/service_providers/_form.html.erb
app/views/service_providers/show.html.erb

Using "public key" is a little misleading since we're actually asking for the public certificate. Added more clear language to state this.

Minor tweak to form to use cert instead of key

---

app/models/service_provider.rb
spec/models/service_provider_spec.rb

This validation should match the IdP: https://github.com/18F/identity-idp/blob/master/app/models/service_provider.rb#L73
This is a quick fix until LG-1410 is implemented to unify this validation for both apps.

Fixes redirect URI validation

---

app/views/layouts/application.html.erb
app/views/users/none.html.erb
config/application.rb

Why:
The UX is not great and we want to better leverage the CRM to handle inbound leads. 
How:
Embeds our CRM's request access form to the unauthorized page.
Also:
Makes the app name more consistent (so it's easier to change in the future!).
<hr>
Before:
After:

Adds access request form to unauthorized page

---

app/models/user.rb
spec/features/groups_spec.rb
spec/models/user_spec.rb
spec/requests/service_provider_api_spec.rb

As a Partner developer who is managing my applications in the Partner dashboard, I want a predictable ordering so it's easier for me to find the application I need to manage.
Before:
After:

LG-939: alphabetize the list of apps in the dashboard

---

Gemfile.lock
app/controllers/service_providers_controller.rb
app/serializers/service_provider_serializer.rb
app/views/service_providers/_form.html.erb
app/views/service_providers/show.html.erb
db/migrate/20190805160021_add_push_notification_url_to_service_provider.rb
db/schema.rb
spec/features/service_providers_spec.rb
spec/models/service_provider_spec.rb

As a partner developer, I want to have a self-service way to configure push notifications in the dashboard, so that I don't have to email Amos or Steve to do it.
Note: ~requires the merging of https://github.com/18F/identity-validations/pull/2 for specs to pass.~ validation gem has been updated and merged.
Note: since we haven't yet merged in the style guide application from LG-1335, there is a TODO in the form partial for how to make the switch.

LG-1272: add push_notification_url to service providers

---

db/seeds.rb

Why: to ensure that we have a consistent admin account in development.

LG-1840: create an admin user on db:seed

---

app/helpers/service_provider_helper.rb
app/views/service_providers/_form.html.erb
app/views/service_providers/_service_provider_yaml.erb
app/views/service_providers/show.html.erb
spec/factories/service_providers.rb
spec/helpers/service_provider_helper_spec.rb

**Why:** So that anyone who wants to update a Service Provider in the IdP can view a formatted YAML text blob in the dashboard on that Service Provider's details page and be able to paste it directly into the IdP service providers configuration.

LG-1815 Generate yaml blob for sp

---

package.json

**Why?**: to match the conditions placed on the idp.

LG-2159: Allow any node version from v8 to v12

---

app/controllers/groups_controller.rb
app/policies/group_policy.rb
app/views/groups/_form.html.erb
app/views/groups/index.html.erb
app/views/groups/show.html.erb
app/views/layouts/application.html.erb
spec/controllers/groups_controller_spec.rb
spec/features/groups_spec.rb
spec/features/nav_links_spec.rb
spec/policies/group_spec.rb

**Why:** Because non-admin users need a way to manage the groups they are members of, and they need the ability to add new users who are not yet in the system directly to their groups.

LG-2126 Allow non-admin users to manage groups, add new users to groups

---

Gemfile
Gemfile.lock
spec/support/capybara.rb

**Why**: Matches idp app, hopefully easier to maintain
This is follow-up from the weird phantomjs issues we saw when upgrading the Ruby version in the other PR (#278)
@jmhooper already removed manually downloading phantomjs, this just switches the webdriver completely to match IDP (see this part of the patch: https://github.com/18F/identity-dashboard/commit/800be3bad02670d4fdc0cee614d3efd9219e75df#diff-1d37e48f9ceff6d8030570cd36286a61L37-L42 )

Switch webdriver to headless chrome

---

config/routes.rb
spec/requests/preserved_urls_spec.rb

Why
We are utilizing 'dashboard group URL' in HubSpot and these links are now broken.
How
Matches /groups/# URLs and redirects to the Teams route.

Preserves groups route

---

.circleci/config.yml
app/views/teams/show.html.erb

LG-2539: Use primary button style for "edit team" button

---

app/controllers/teams_controller.rb
app/controllers/users/omniauth_controller.rb
app/helpers/team_helper.rb
app/policies/team_policy.rb
app/views/teams/_teams_list.html.erb
app/views/teams/index.html.erb
config/initializers/simple_form.rb
lib/tasks/service_providers.rake
package.json
spec/controllers/teams_controller_spec.rb
spec/controllers/users/omniauth_controller_spec.rb
spec/policies/team_policy_spec.rb
yarn.lock

**Why:** Certain users whose emails end in .gov, .mil, or .fed.us are allowed to create teams so they can get started on the dashboard right away.
Also some updates were made (even for non-whitelisted users) to fit these permissions... in particular regarding the deletion of a team:
https://docs.google.com/document/d/17gh18BoeJ84ZZKX_z78xuDGHk4Lko9AfcvtctOqT-y4/edit#

LG-2706 whitelisted users can create/manage teams

---

app/helpers/team_helper.rb
app/policies/team_policy.rb
app/views/teams/_teams_list.html.erb
spec/policies/team_policy_spec.rb

**Why?** Because we don't want non-admins to accidentally delete teams

LG-2770 only admins can delete teams

---

config/webpacker.yml

**Why**: This app and the IdP try to listen to the dev server on the same port. This causes lots of funny stuff to happen with the assets. Bumping the port the dashboard uses up 1 fixes this.

Change the port that webpack-dev-server uses from the default

---

config/initializers/secure_headers.rb
config/webpacker.yml

**Why**: We changed the webpack dev server to use port 3036 so it doesn't collide with the IdP. This commit updates that port in a few places I missed.

Fix the dev server port in more places

---

config/environments/production.rb

We see this error when deploying the dashboard
```
NameError: uninitialized constant SMTP_SETTINGS
/srv/dashboard/releases/20200318230821/config/environments/production.rb:72:in `block in <top (required)>'
```
My suspicion is that it's got something to do with the Rails 5.2 upgrade, but this is a minimal patch that will let us continue to deploy the dashboard (verified by patching on a box)

Add explicit require to fix undefined constant SMTP_SETTINGS

---

app/assets/stylesheets/application.css.scss.erb
app/views/emails/index.html.erb
app/views/layouts/application.html.erb
app/views/service_providers/all.html.erb
app/views/service_providers/index.html.erb
app/views/teams/edit.html.erb
app/views/teams/index.html.erb
app/views/users/index.html.erb
package.json
yarn.lock

**Why:** Because we were forcing button styles on our buttons since the design system was overriding them with form link styles. Since we updated the design system, we are removing the custom styles from the dashboard.
Also I removed the overarching `usa-prose` class after discovering it can clash with some non-usa-prose styles, and it was being applied to pages which are not comprised of longform text (which is what usa-prose is intended for https://design.login.gov/typography/ )

LG-2788 Upgrade to latest style guide with button fixes

---

config/environments/production.rb

**Why**: Because if local storage is disabled the configs for the Amazon adapter most likely are not present

Don't use the amazon adapter for active storage if logo upload is disabled

---

app/views/teams/_teams_list.html.erb
app/views/teams/edit.html.erb

**Why:**  We want admins to see links to team members' profiles in the teams card, and we want partners to only see a team member count on the card.

LG-2795 Create separate team card views for admins and partners

---

app/controllers/home_controller.rb
app/controllers/service_providers_controller.rb
app/controllers/teams_controller.rb
app/helpers/service_provider_helper.rb
app/policies/service_provider_policy.rb
app/policies/team_policy.rb
app/views/home/authenticated/index.html.erb
app/views/layouts/application.html.erb
app/views/teams/_teams_list.html.erb
app/views/teams/all.html.erb
config/routes.rb
spec/features/teams_spec.rb
spec/helpers/service_provider_helper_spec.rb

**Why?**  We want admins to have an easy-to-read landing page on the dashboard that only includes the teams of which they are members, rather than all Partnership teams on the landing page.
Snuck some other things into this PR:
- Make separate pages for an admin user's teams and an admin-only view of "All teams" ([LG-2815](https://cm-jira.usa.gov/browse/LG-2815))
- Restricted access for 'all' pages to admins only (like the new `/teams/all`, and `/service_providers/all`, which was accessible by any partner before)
- Updated buttons for apps on team cards ([LG-2814](https://cm-jira.usa.gov/browse/LG-2814))
- Allow "0" label to show when there are no apps on a team card ([LG-2817](https://cm-jira.usa.gov/browse/LG-2817))
- Quick fix to admin SP yaml blurb ('cert' key is correct) …

LG-2813 Improve admin landing page, and other improvements

---

config/agencies.yml

**Why:** Because we want state/local/tribe users to be able to select a generic agency when creating a team.

LG-2863 Add generic agency option

---

app/views/home/authenticated/index.html.erb
app/views/teams/_no_teams.html.erb
app/views/teams/index.html.erb

**Why:** On the landing page, we want whitelisted partners and admins to see a CTA when they don't have any teams.

LG-2818 Add teams card

---

app/controllers/teams_controller.rb
config/locales/en.yml
spec/features/teams_spec.rb

**Why:** Because we don't want to delete teams which still have apps attached to them, therefore orphaning those apps.

LG-2882 prompt user to delete apps before deleting non-empty team

---

app/assets/stylesheets/application.css.scss.erb

Why? so the text on new/edit team and new/edit app for labels and values are different

LG-2511 changing color of label text to be different from input text on forms

---

app/views/layouts/application.html.erb
config/locales/en.yml

**Why:** Because we want partners to see sign in/sign out buttons that will be consistent with new partners site sign in button.

LG-2816 Change log in/logout to sign in/sign out

---

app/views/service_providers/_form.html.erb
app/views/service_providers/show.html.erb
config/application.yml.example
config/environments/development.rb
config/environments/production.rb
config/storage.yml
spec/features/logo_upload_spec.rb

Given the difficulty in sorting out how to actually push out changes to figaro settings without a devops PR, we're going to simply turn on logo uploads by default. They may still be turned off via figaro, and the bucket is still configurable via figaro.
If I can get this merged asap, I'll test out in `dev` prior to it getting auto deployed to `int`.

LG-2871: have logo uploads enabled by default

---

app/views/service_providers/_form.html.erb
app/views/service_providers/show.html.erb
config/application.yml.example
config/environments/development.rb
config/environments/production.rb
config/storage.yml
spec/features/logo_upload_spec.rb

This reverts commit 9d8b157baa678fa6089a9a9f5860cbacf77a3000.
The logo upload is failing with a 413: Request Entity Too Large, so we need to back it out. It's currently live on `int`

Revert "LG-2871: have logo uploads enabled by default (#328)"

---

Gemfile
Gemfile.lock

The current infrastructure design has the standard log file being streamed to AWS CloudWatch. Early on in development, the dashboard was outfitted with the `rails_12factor` gem that, among other things, pulls in the `rails_stdout_logging` gem and forces the Rails logger to write to STDOUT. As such, we've had no access to the deployed dashboard logs since at least March 2018.
For now, we should back out the `rails_stdout_logger` gem and log to the default log file.

LG-2954: stop logging to STDOUT in production

---

app/views/service_providers/_form.html.erb
app/views/service_providers/show.html.erb
config/application.yml.example
config/environments/development.rb
config/environments/production.rb
config/storage.yml
spec/features/logo_upload_spec.rb
spec/features/service_providers_spec.rb

PR #329 reverted the default enabling of logo uploads for partners. That was necessary because we didn't have a convenient way to turn off the feature, and the uploads were blocked by our body size limit of 10k (most logo files are bigger than 10k). The upload limit has been increased to 2MB, so we should be able to run with this now.

LG-2871: ready for logo uploads to go live

---

.rubocop.yml
app/views/service_providers/_form.html.erb
app/views/service_providers/show.html.erb
config/environments/development.rb
config/environments/production.rb
config/initializers/active_storage.rb
config/storage.yml

I had disabled logo upload in `int` - that is reversed.
Went back to `Figaro.env` calls vs. `ENV.fetch...`
Configured `development` to use local storage (logos won't be available to idp)
Configured active storage to make service urls expire in 1 week (was 5 min :-o)

LG-2960: clean up logo upload

---

app/services/service_provider_logo_updater.rb
spec/services/service_provider_logo_updater_spec.rb

This service class was in support of the rake task that imported all of the existing SP logos into ActiveStorage. We'll likely never need it again, but this includes the update I made live on the deployed server to get the content-type to be served out by S3.

update logo updater service object to match what was run on int env

---

app/controllers/users/omniauth_controller.rb
config/application.yml.example
spec/controllers/users/omniauth_controller_spec.rb

As a partner with a `.gov` or `.mil` email address, I don't want to have to email Tom to get access to the login.gov dashboard so I can get started right away. 
Whitelisted TLDs are configurable via `application.yml`. Note, they actually don't have to be TLDs, just the end of the email, e.g., `sa.gov` would whitelist `gsa.gov` and `nasa.gov`.

LG-2971: auto-create account for .gov or .mil users

---

app/controllers/users/omniauth_controller.rb
config/application.yml.example

Removes the tld whitelist from the default so that we can more precisely control each env via app.yml.

LG-2791: doesn't specify a whitelist of allowed tld's in deployed envs

---

app/forms/manage_users_form.rb
spec/features/manage_users_spec.rb
spec/forms/manage_users_form_spec.rb

**Why?** Adding an existing user to the dashboard does not work with uppercase characters.

LG-3048: use case insensitive seach when adding emails to a team

---

app/controllers/api/service_providers_controller.rb
app/serializers/service_provider_serializer.rb
spec/controllers/api/service_providers_controller_spec.rb
spec/serializers/service_provider_serializer_spec.rb

**Problem**
in INT dashboard `urn:gov:dhs.cbp.jobs:openidconnect:aws-goes-dev` and`urn:gov:dhs.cbp.pspd:openidconnect:pspd-ttp-dev` have the same agency/team, but in IDP they don't
The issue is that the IDP pulls `agency_id` out of JSON, which was being pulled as a direct attribute, but in dashboard this should come from the team association.
**Solution**
Fix the JSON serializer

Pull agency_id from team, so it correctly updates in JSON to the IDP

---

app/controllers/users_controller.rb
app/models/user.rb
app/validators/user_validator.rb
app/views/users/new.html.erb
config/locales/en.yml
spec/models/user_spec.rb

Surprisingly, the original User model validation:
```
validates :email, uniqueness: true
```
Does not leverage `act_as_paranoid` to add the `deleted_at` query scope:
So I added a custom validator that works:
```
validates_with UserValidator, on: :create
```
There are currently no Spanish/French translations in the app, so I didn't break the trend.  I just updated/normalized `config/locales/en.yml`.

Add soft deletion to User model

---

app/controllers/teams_controller.rb
spec/controllers/teams_controller_spec.rb
spec/features/teams_spec.rb

**Why**: When I put together the manage users story I left some things off
**How**:
- Fix a 500 that prevents people from creating a team after the manage users change
- Redirect to the "Manage Users" page after creating a team

Cleanup partner self-service onboarding

---

app/views/service_providers/_form.html.erb

The current verbiage is out of date as to what is available for IAL1.

point to developers.login.gov for user attributes

---

app/controllers/service_providers_controller.rb
app/helpers/service_provider_helper.rb
app/views/service_providers/_allow_prompt_login.html.erb
app/views/service_providers/_form.html.erb
app/views/service_providers/show.html.erb
db/migrate/20201130171218_add_allow_prompt_login_to_service_providers.rb
db/schema.rb
spec/features/service_providers_spec.rb
spec/helpers/service_provider_helper_spec.rb

Add boolean allow_prompt_login attribute to the service_providers table
that defaults to false, matching what the IdP has. Conditionally add
checkbox field for admins on the service provider form to allow editing
of that attribute, and also authorize editing of that attribute at the
controller level. Finally, add display for this attribute in the show
view.
Includes a feature spec for the happy path and unit tests for a new
helper method for the show view.

[LG-2898] Allow admins to enable prompt=login for SPs

---

app/controllers/service_providers_controller.rb
spec/controllers/service_provider_controller_spec.rb
spec/controllers/users/sessions_controller_spec.rb

Implemented by @mitchellhenke, I independently verified that uploading SVG logos worked in his personal sandbox environment.

Remove content-type push for uploaded logos

---

app/javascript/packs/validate-logo-size.js
app/views/service_providers/_logo_upload.html.erb

Warn partners if they select a file greater than 1MB in size. We could
also add all sorts of other client-side validations but keeping it
simple for now.

[LG-3733] Add client-size validation of logo size

---

app/controllers/manage_users_controller.rb
app/forms/manage_users_form.rb
spec/forms/manage_users_form_spec.rb

Resolves LG-3686
Adds a validation to the ManageUsersForm to check that at least one
email address is submitted. Also updates ManageUsersController#create to
pass in an empty array instead of nil when no emails are passed.

[LG-3686] Validate that at least one user is added to a team

---

app/controllers/service_providers_controller.rb
app/models/service_provider.rb
app/serializers/service_provider_serializer.rb
app/views/service_providers/_form.html.erb
app/views/service_providers/show.html.erb
db/migrate/20210122185518_add_default_aal_to_service_providers.rb
db/schema.rb
spec/features/service_providers_spec.rb
spec/serializers/service_provider_serializer_spec.rb

Allow partners to set the default AAL level via the dashboard. This value is used if no AAL value is specified explicitly in the request.
Adds an select input to the SP form to choose a level, and shows it when viewing the SP.

Adds default_aal to service_provider (LG-3825)

---

README.md

**Why**: As a developer contributing to identity-dashboard, I want to know what to do when I log in for the first time and encounter a "No account exists" warning page, so that I'm not left confused and forced to resort to scouring through source code to figure out how to use the application.

Improve first-run documentation guidance

---

app/views/service_providers/_form.html.erb

This results in us sending back `http://idmanagement.gov/ns/assurance/aal/1` instead of `urn:gov:gsa:ac:classes:sp:PasswordProtectedTransport:duo`

HOTFIX: save blank AAL as nil, not 1

---

config/newrelic.yml

**Why**: So dashboard can start managing its own NewRelic.yml instead of depending on the chef to write it one

Change the newrelic.yml to match other repos and prod config

---

app/serializers/service_provider_serializer.rb
spec/serializers/service_provider_serializer_spec.rb

Reverts 18F/identity-dashboard#413, do not merge until `certs` is re-enabled in the IdP (https://github.com/18F/identity-idp/pull/4898)

[LG-4479] Revert "Switch Dashboard to only push the latest cert"

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.css.scss.erb
app/controllers/api/security_events_controller.rb
app/controllers/security_events_controller.rb
app/forms/security_event_form.rb
app/models/security_event.rb
app/models/user.rb
app/policies/security_event_policy.rb
app/services/idp_public_keys.rb
app/services/user_session.rb
app/views/layouts/application.html.erb
app/views/security_events/_table.html.erb
app/views/security_events/all.html.erb
app/views/security_events/index.html.erb
app/views/security_events/show.html.erb
app/views/service_providers/_certificate.html.erb
config/routes.rb
db/migrate/20210412181322_create_security_events.rb
db/schema.rb
spec/controllers/api/security_events_controller_spec.rb
spec/controllers/security_events_controller_spec.rb
spec/factories/security_event.rb
spec/forms/security_event_form_spec.rb
spec/models/security_event_spec.rb
spec/models/user_spec.rb
spec/policies/security_event_policy_spec.rb
spec/services/idp_public_keys_spec.rb
spec/views/security_events/_table.html.erb_spec.rb

- Record them in the DB
- Show them in the UI
Here's a little tour!
* **Note**: I remembered to add the details/summary CSS fix after I took screenshots, so the triangle *is* there correctly
| notes | screenshot |
| --- | ---- |
| New nav item, view a table of security events for yourself | <img width="1031" alt="Screen Shot 2021-04-12 at 4 42 02 PM" src="https://user-images.githubusercontent.com/458784/114476040-5b1a5800-9bae-11eb-9ea1-ae4a77b1409d.png"> |
| mouse over the event name to see the full name | <img width="576" alt="Screen Shot 2021-04-12 at 4 42 28 PM" src="https://user-images.githubusercontent.com/458784/114476117-84d37f00-9bae-11eb-97a3-03b3c8c97f11.png">  | good ol' details/summary to see the full payload |  <img width="1081" alt="Screen Shot 2021-04-12 at 4 43 33 PM" …

Accept RISC Security Event Tokens (LG-4413)

---

app/helpers/security_event_helper.rb
app/services/dev_docs.rb
app/services/idp_public_keys.rb
app/views/security_events/_table.html.erb
app/views/security_events/show.html.erb
config/application.yml.example
spec/helpers/security_event_helper_spec.rb
spec/services/dev_docs_spec.rb
spec/services/idp_public_keys_spec.rb
spec/views/security_events/_table.html.erb_spec.rb

Feedback from going through this with @juliaelman 
- Drop UUID from table, it's not useful
- Load friendly names for events if we can (from dev docs PR: https://github.com/18F/identity-dev-docs/pull/178)
- Load descriptions for event if we can
Next PR
- Adding search to the table
Screenshots
| before | after |
| --- | --- |
| ![Screen Shot 2021-04-15 at 8 59 05 AM](https://user-images.githubusercontent.com/458784/114900968-33530c00-9dc9-11eb-8722-3086ca557721.png) | <img alt="Screen Shot 2021-04-15 at 8 58 40 AM" src="https://user-images.githubusercontent.com/458784/114900994-3817c000-9dc9-11eb-9266-92a9edbbd996.png"> |
| <img alt="Screen Shot 2021-04-15 at 8 59 13 AM" src="https://user-images.githubusercontent.com/458784/114901039-436aeb80-9dc9-11eb-9500-f5cecc713604.png"> | <img …

UX feedback: clean up security events pages (LG-4414)

---

app/helpers/service_provider_helper.rb
app/models/service_provider.rb
app/views/service_providers/show.html.erb
spec/helpers/service_provider_helper_spec.rb

Resolves LG-4072
Add ServiceProviderHelper#sp_attribute_bundle to filter out invalid attributes from the show view

[LG-4072] Remove middle_name from attribute bundle input

---

config/environments/production.rb

**Why**: the default is a file store, and we don't have
permission to write to the tmp directory it uses
I tested this out on a `dev` box to make sure the config was acceptable
[NewRelic error link](https://one.newrelic.com/launcher/nr1-core.explorer?pane=eyJiYXJjaGFydCI6ImJhcmNoYXJ0IiwidG9wRmFjZXQiOiJ0cmFuc2FjdGlvblVpTmFtZSIsInBhZ2UiOiJzaG93IiwicHJpbWFyeUZhY2V0IjoiZXJyb3IuY2xhc3MiLCJ0cmFjZUlkIjoiOTFhZWY4NTUtOWVkZC0xMWViLWExOGItMDI0MmFjMTEwMDA4XzE3NDQxXzI0ODg3IiwiZmlsdGVycyI6W3sia2V5IjoiZXJyb3IuZXhwZWN0ZWQiLCJ2YWx1ZSI6Im5vdCB0cnVlIn0seyJrZXkiOiJlcnJvci5jbGFzcyIsInZhbHVlIjoiRXJybm86OkVBQ0NFUyIsImxpa2UiOmZhbHNlfV0sIm5lcmRsZXRJZCI6ImVycm9ycy11aS5vdmVydmlldyIsImVudGl0eUlkIjoiTVRNM05qTTNNSHhCVUUxOFFWQlFURWxEUVZSSlQwNThNVEE0T0RnMU9UUXgifQ==&sidebars[0]=eyJuZXJkbGV0SWQiOiJucjEtY29yZS5hY3Rpb25zIiw …

Use an in-memory cache store in production

---

lib/tasks/dev.rake

**Why**: So the `make setup` works as expected
**How**: The dev:prime task was having issues with a foreign key constraint on the agencies table. This commit avoids that by using an agency that is added by the agency seeder.

Fix the setup:script

---

app/models/team.rb
spec/features/manage_users_spec.rb

Resolves LG-4224
Even though the join records were being destroyed when removing a user
from a team, PaperTrail wasn't being triggered and no version was being
saved. This commit adds `dependent: :destroy` to the `has_many :users`
association for Teams, which properly triggers the PaperTrail callback.

[LG-4224] Ensure that PaperTrail tracks user management events

---

Gemfile
config/application.yml.example
config/initializers/rack_timeout.rb

**Why**: So that the configuration for rack-timeout matches the configuration in the IDP and in PKI

Stop using env vars to configure rack timeout

---

bin/activate

**Why**: It was removed in a previous commit

Don't invoke Deploy::Activate in bin/activate

---

bin/activate

**Why**: My last commit had a bug where we were trying to run bash in a ruby script

Fix bin/activate and make sure it works

---

app/services/risc_destination_updater.rb

Turns out this was needed after all (tried this in the console just now)

Add AWS region to EventBridge client

---

app/services/risc_destination_updater.rb
spec/services/risc_destination_updater_spec.rb

Here's my mental model of what I'm trying to create (the boxes in blue)
I went a lot lighter on the test coverage this time because at the end of the day it's all stubbed, and more tests won't catch misconfigurations

Update RiscDestinationUpdater to handle more AWS object graph

---

app/controllers/service_providers_controller.rb
app/helpers/service_provider_helper.rb
app/views/service_providers/_email_nameid_format_allowed.html.erb
app/views/service_providers/_form.html.erb
app/views/service_providers/show.html.erb
db/migrate/20210614190137_add_email_name_id_format_to_service_providers.rb
db/schema.rb
spec/features/service_providers_spec.rb

Resolves LG-4666
* Add email_nameid_format_allowed column to service_providers table
* Update strong params and add controls to edit and view the attribute
if you're an admin
* Add basic feature specs

[LG-4666] Add email NameID format config to SPs

---

app/javascript/app/service-provider-form.js
app/models/service_provider.rb
app/views/service_providers/_form.html.erb
app/views/service_providers/show.html.erb
config/initializers/inflections.rb
spec/models/service_provider_spec.rb

Resolves LG-4446
* Adds additional enumerated option for protocol and updates the generic
OIDC option to specify private_key_jwt.
* Update JS to appropriately hide the certificate fields when OIDC PKCE
is selected
* Add necessary acronyms to ActiveSupport::Inflector

[LG-4446] Add PKCE option to service provider form

---

app/services/risc_destination_updater.rb
spec/services/risc_destination_updater_spec.rb

Ran into another issue testing in my env
I wish we had another stable identifier for these besides DB ID, but this is what we have for now
Luckily the IDP does not need to reference these IDs (because they'd be different on the IDP side anyways), they just need to be consistent from the side of whatever manages these, which is Dashboard vs Dashboard.

Update EventBridge names to fit within 64 character limit

---

Gemfile.lock

**TL;DR**: Installs Bundler 2.20.0 in this repo, and updates version within `Gemfile.lock` accordingly, via:
```
gem install bundler:2.20.0
bundle update --bundler
```
No additional gems are affected. Hosts that build from this branch use Bundler 2.20.0 when running `rbenv exec bundle install` during build time.
Output from commands on an `idp` instance built off the `bleachbit` branch of `identity-devops`, which uses the `jp/bundler-2-electric-boogaloo` branch for all repos:
```
$ which bundler
/opt/ruby_build/shims/bundler
$ bundler -v
Bundler version 2.2.24
$ gem info bundler
*** LOCAL GEMS ***
bundler (2.2.24, 1.17.2)
Authors: André Arko, Samuel Giddins, Colby Swandale, Hiroshi
Shibata, David Rodríguez, Grey Baker, Stephanie Morillo, Chris
Morris, James Wen, Tim Moore, André Medeiros, …
```

updating to Bundler 2.20.0 in Gemfile.lock

---

app/helpers/service_provider_helper.rb
spec/helpers/service_provider_helper_spec.rb

This is correcting some mistakes not covered in #474 . 
- IAL should now be set to a integer
- Conditional attributes for SAML v OIDC should now be populated with the correct data

Correcting yaml blob conditional attributes and ial number as an integer

---

app/helpers/service_provider_helper.rb

Simply removing the app_id assignment and having the `restrict_to_deploy_env` variable display with quotes in the yaml blob.  There will be more changes with a serializer coming up but due to the glacier development pace on the partnerships team I am not sure when I'll get to it.  I think that this will cause errors if I don't fix it now and the rest is more cosmetic rather than functional.

Remove app_id assignment in yaml blob

---

.circleci/config.yml

An email from CircleCI:
> As of Dec 31, 2021, legacy images will no longer be supported on CircleCI

Update CircleCI ruby image (LG-5120)

---

spec/factories/service_providers.rb
spec/features/service_providers_spec.rb

Piggy-backing off of https://github.com/18F/identity-dashboard/pull/495
-   Add test for toggling protocol on saml service providers does not lose user entered saml data

Add test for toggling protocols when editing service providers

---

app/javascript/app/service-provider-form.js
app/views/service_providers/_form.html.erb
config/locales/simple_form.en.yml
spec/factories/service_providers.rb
spec/features/service_providers_spec.rb

https://cm-jira.usa.gov/browse/LG-5083
- Add front end changes to make return_to_sp_url a required field for all SAML integrations
- Hide return_to_sp_url for OIDC integrations and make the field not required so that SPs can submit the form
- Update unit tests
- Update field content

Return to app url is a conditionally required field

---

app/helpers/service_provider_helper.rb
spec/factories/service_providers.rb
spec/helpers/service_provider_helper_spec.rb

https://cm-jira.usa.gov/browse/LG-5270
-  Conditionally adding `signed_response_message_requested` and `email_nameid_format_allowed` fields to yaml blob when selected
- The code is symptomatic of other underlying problems that we are choosing to not deal with at this time

[LG-5270] conditionally adding saml attributes to yaml blob

---

config/status_checks.yml
spec/support/deploy_status_checker_helper.rb

I'm appdev oncall (aka deployer) this week, and I wanted a quick way to see if there were pending changes to the PKI app I should deploy, so I figured this was worth adding.
**Note**: Will likely need a proxy change in devops to allow these requests to work

Add PKI service to deploy dashboard

---

app/controllers/service_providers_controller.rb
spec/controllers/service_providers_controller_spec.rb

https://cm-jira.usa.gov/browse/LG-5703
-   For empty/null certs, do not add them to the SP cert array or they WILL save as null certs to the SP

[LG-5703] Do not upload empty/null certs to Dashboard config

---

app/javascript/app/service-provider-form.js
spec/features/service_providers_spec.rb

This commit starts converting some of the functionality in the service provider form to vanilla JS. This is intended to allow us to drop jQuery as a dep from the dashboard.

Start converting jQuery code to plain old fashioned javascript

---

README.md

LG-7655
https://docs.google.com/document/d/1pY9u2y0SnlMr4sgypd-kM8eDy6Sh0_zFUUy0DpXzA90/edit#
This pull request adds the branching strategies developed as part of the LG-7655 research to the README.

Add branching strategy to the README

---

Gemfile.lock

mail 2.8.0 has an [issue](https://github.com/mikel/mail/issues/1489) with file permissions that is causing deploy issues so this PR reverts us back to 2.7.1

revert mail gem to 2.7.1

---

app/controllers/teams/users_controller.rb
config/database.yml

This is not a ticket but something I realized while chatting with Oren that I misunderstood from earlier code review ([regarding queries for team and user in users.controller.rb](https://github.com/18F/identity-dashboard/pull/607/files#r1082075398))
Removing team_and_users method, adding includes(:users) to team method, and updating user method to use team method. Basically a little bit of cleanup
- All PRs …

Quick Fix simplify team/users queries

---

app/assets/stylesheets/application.css.scss.erb
app/views/service_providers/_form.html.erb
config/locales/service_providers.en.yml

https://cm-jira.usa.gov/browse/LG-9180
Adding a `text-heavy` class, and applying it to two field hints for the service_provider form.

LG-9180: Add font-weight to app name and friendly name fields

---

config/initializers/simple_form.rb

Replaces `.usa-form-hint` with `.usa-hint`.
`.usa-form-hint` is a legacy class name from USWDS v1, replaced in USWDS v2 with `.usa-hint` ([documentation](https://designsystem.digital.gov/documentation/migration-v2/#inputs)).
We still define custom styles for this class in the Login.gov Design System ([source](https://github.com/18F/identity-style-guide/blob/4b8c38eccb0ddec64a3d87ce76cc31f07a4c56a0/src/scss/components/_inputs.scss#L233-L237)), but I'd like to remove these styles, and this appears to the only instance in use I could find.
This **does** have a visual impact, but it is intended to bring into alignment with hints on other Login.gov sites. If needed, we could add additional utility classes to restore the original style.
**Effective styles:**
_Before:_
```css
.usa-form-hint { …
```

Replace deprecated USWDS v1 form hint class

---

Gemfile

#630 added the `saml_idp`, but only in test/dev environments, so the application crashes when reaching this [line](https://github.com/18F/identity-dashboard/blob/258ada40bfb761376f735afe1de3050e074d6f67/app/controllers/tools_controller.rb#L2) when deployed in production.
This PR moves the gem into the default group.

Move saml_idp to default gem group so it can be used in production

---

app/controllers/api/service_providers_controller.rb

There's currently an N+1 query that causes us to hit the active_storage_blobs table for each row in service_providers (could be hundreds of individual queries). This change adds that table to the preload so that it is all loaded in one query.
```
D, [2023-04-27T19:34:18.909681 #12917] DEBUG -- :   ActiveStorage::Blob Load (0.8ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 2677], ["LIMIT", 1]]
D, [2023-04-27T19:34:18.911386 #12917] DEBUG -- :   ActiveStorage::Blob Load (0.7ms)  SELECT "active_storage_blobs".* FROM "active_storage_blobs" WHERE "active_storage_blobs"."id" = $1 LIMIT $2  [["id", 1490], ["LIMIT", 1]]
D, [2023-04-27T19:34:18.913152 #12917] DEBUG -- :   ActiveStorage::Blob Load (0.6ms)  SELECT …
```

Fix N+1 query on logos for service_providers API endpoint

---

app/views/service_providers/show.html.erb

Some of our internalization strings include HTML but weren't being rendered in HTML. This will force Ruby to render the HTML instead of just printing it out to the user.
Before:
After:
1. [X] Have you linted and tested your code locally prior to submission?
3. [X] Have you linked to any relevant tickets or conversations?

Make strings that have HTML to render as HTML

---

app/controllers/api/service_providers_controller.rb
app/serializers/service_provider_serializer.rb
spec/controllers/api/service_providers_controller_spec.rb
spec/serializers/service_provider_serializer_spec.rb

the first attempt to add the protocol attribute led to a bug where partners hit errors when they tried to update their config https://github.com/18F/identity-dashboard/pull/649
this time, we only pass the protocol attribute through if the serializer is being called via our show endpoint.
added a :show option to the Serializer

lg-9761 update serializer to include protocol attribute one more time with feeling

---

app/controllers/teams_controller.rb
app/views/teams/edit.html.erb
spec/controllers/teams_controller_spec.rb

https://cm-jira.usa.gov/browse/LG-10145
When a non-admin user tried to update team information, it would delete all the users except that team member. This change adds a hidden_field_tag to pass the existing team's user ids through in order to make sure they are all present in an update.

LG-10145 Fix bug that deletes users in update path

---

app/helpers/service_provider_helper.rb
app/serializers/service_provider_serializer.rb
config/application.yml.default
lib/identity_config.rb
spec/serializers/service_provider_serializer_spec.rb

The (hopefully) final large change for [SBAR misconfiguration work](https://docs.google.com/document/d/1oi5FyJqzH-yA5nR6mC_AcDhEp-avpLoZTzYQelPoP5M/edit)
Currently, the dashboard does not send the `pkce` attribute via the API when service providers are updated. The result of this is that all IDP environments that use the dashboard application will have service providers where the `pkce` value is always `nil`. This can be confusing and lead to issues when promoted to production though this is mitigated by [this change](https://github.com/18F/identity-idp-config/pull/1709) in the identity-idp-config repository.
- Passes true or false in the `pkce` attribute with a couple of exceptions (drawn from a similar one [here](https://github.com/18F/identity-idp-config/blob/dfd066f/lib/models/service_ …

Send PKCE attribute in service providers API so it is updated in the IDP

---

app/controllers/service_providers_controller.rb
app/models/service_provider.rb
app/services/service_provider_updater.rb
spec/controllers/service_providers_controller_spec.rb
spec/services/service_provider_updater_spec.rb

https://cm-jira.usa.gov/browse/LG-10062
This change updates the service_provider save code flow so that a single service provider is sent to the IDP to be synced in the sandbox, creating a much faster "publish." 
This change has a[ corresponding PR](https://github.com/18F/identity-idp/pull/9032) in the IDP that should be merged in first.

Pass single service_provider to sync

---

app/services/service_provider_updater.rb
spec/services/service_provider_updater_spec.rb

https://cm-jira.usa.gov/browse/LG-10062
This ticket surfaced an issue where, when JSON requests are over 20k, they are automatically rejected by nginx. We raised the nginx threshold, but also would like to compress requests to make sure the requests stay below the threshold.
This ticket should be merged in AFTER https://github.com/18F/identity-idp/pull/9074

Compress Service Provider request

---

app/javascript/packs/service_provider_form.js
app/views/service_providers/_form.html.erb

https://cm-jira.usa.gov/browse/LG-10585
When running through acceptance steps, I noticed that the input was being marked as required and a user needed to include it to submit an IdV configuration, but the `*required` label was not being added initially. This solves that UX bug.

Ensure that required label is present

---

app/views/service_providers/_form.html.erb
config/locales/service_providers.en.yml

[LG-11024](https://cm-jira.usa.gov/browse/LG-11024) Add help text for `active` field
Added help text to the `active` field in the configuration form based on the feedback received from [the research document](https://docs.google.com/document/d/1XY-77y3ImPuW_D8JMn_psCfAabsjHTv6Z0HJueyx1qU/edit)
1. [X] Have you linted and tested your code locally prior to submission?
2. [X] Have you tagged the appropriate dev(s) for review?
3. [X] Have you linked to any relevant tickets or conversations?

Add help text to the active config option

---

Gemfile
Gemfile.lock

https://cm-jira.usa.gov/browse/LG-10951
When looking through all the PRs listed in the ticket, I found a few more ruby updates that were not in the Dependabot vulnerability view, but still had some vulnerabilities attached to them.
I was unable to include an update to `json-jwt` because this error happened when I tried to `bundle` -- this seems like a bigger can of worms.
```
Because every version of omniauth_login_dot_gov depends on faraday ~> 0.17
and json-jwt >= 1.16.0 depends on faraday ~> 2.0,
every version of omniauth_login_dot_gov is incompatible with json-jwt >= 1.16.0.
So, because Gemfile depends on json-jwt >= 1.16.0
and Gemfile depends on omniauth_login_dot_gov >= 0,
version solving has failed.
```
2. [ ] …

More ruby updates

---

config/oidc.yml

Related to the discussion and changes in https://github.com/18F/identity-idp-config/pull/1928
This PR reverts #688 so that the dashboard uses a static `client_id`

Use static client_id (Reverting #688)

---

app/controllers/service_providers_controller.rb
app/models/service_provider.rb
spec/models/service_provider_spec.rb

https://cm-jira.usa.gov/browse/LG-10885
This ticket is in conjunction with https://github.com/18F/identity-devops/pull/6904
Adds a validation to the logo image to ensure it's under 1mb 
Also deletes some code that is not being invoked

LG-10885 413 error on creating a new integration

---

app/views/service_providers/_form.html.erb

[LG-11452](https://cm-jira.usa.gov/browse/LG-11452)
Fix the Failure to Proof hint so that the link is clickable, instead of printing out the HTML.

Fix failure to proof hint so the link displays as a link

---

db/migrate/20210401171237_move_saml_client_cert_to_certs.rb
db/migrate/20210401225415_remove_service_providers_saml_client_cert.rb

Slack discussion [here](https://gsa-tts.slack.com/archives/C01SU3NB9T3/p1704823624349349)
This is a follow up to #707 to fix some class names that are being improperly inflected due to the casing of the class name.

Fix casing of database migration class names to match file names

---

.gitlab-ci.yml

Swaps from the default pull policy of `IfNotPresent` to `Always` for images that are referencing `main` to prevent stale containers from hanging around and being used.

Updating pull policy from IfNotPresent to Always to prevent stale images

---

app/assets/stylesheets/application.css.scss.erb
app/views/layouts/application.html.erb
config/initializers/assets.rb

The logo was not showing up in the [production partner dashboard](https://dashboard.int.identitysandbox.gov/) 
https://cm-jira.usa.gov/browse/LG-11787
I updated it to match how it looks in the navigation in the [dev docs](https://developers.login.gov/) (hopefully also better for accessibility) . It is an image tag now rather than being a background image (which was not showing up previously) .
- All PRs must …

LG-11787 Logo branding 

---

app/controllers/service_providers_controller.rb
app/views/service_providers/_form.html.erb

[LG-12042](https://cm-jira.usa.gov/browse/LG-12042)
The last PR pertaining to this made it so users cannot see what their current help text looks like. This fixes it, giving them a read only view. 

LG-12042  users can still see but not edit help text

---

app/controllers/service_providers_controller.rb
app/views/service_providers/_form.html.erb

https://cm-jira.usa.gov/browse/LG-12420
This updates the help text inputs to be correctly formed.
https://github.com/18F/identity-dashboard/pull/728 broke the input fields. This happened because it updated sinatra, which updated the production rack version. The rack change included a [bug fix](https://github.com/rack/rack/blob/main/CHANGELOG.md#fixed-1) to [fix Utils.build_nested_query](https://github.com/rack/rack/pull/1989). (thanks andrew for finding the specific issue)
There was a bug in our form code that relied on THAT bug to work. This fixes that bug!
Before:
After:
- Consider using …

Updates help text form to correctly nest attributes

---

app/serializers/service_provider_serializer.rb
config/application.yml.default
config/application.yml.default.docker
lib/identity_config.rb

https://cm-jira.usa.gov/browse/LG-12448
Removes conditional in serializer that allowed specific integrations to have PKCE as `nil`
Remove related config key from configuration

LG-12448 Remove conditional exception

---

app/controllers/security_events_controller.rb
app/views/layouts/application.html.erb
spec/controllers/security_events_controller_spec.rb
spec/features/nav_links_spec.rb

[LG-11789](https://cm-jira.usa.gov/browse/LG-11789)
Removes `Security Events` from the navigation for non-admin users. For non-admin users who have the URL saved, they'll receive a `401 Unauthorized` response. For admin users, nothing changes from its current form.
This PR completely removes the Security Events link from the navigation only for non-admin users.
If this PR is accepted, #736 should be cancelled.
1. [X] Have you linted and tested your code locally prior to submission?
2. [X] Have you tagged the appropriate dev(s) for review?
3. [X] Have you linked to any relevant tickets or conversations?
- Ideally, PRs should be reviewed by at least 2 team …

Remove Security Events from non-admin users navigation (option 1)

---

app/controllers/api/service_providers_controller.rb
app/controllers/service_providers_controller.rb
app/views/service_providers/all.html.erb
config/routes.rb
spec/controllers/api/service_providers_controller_spec.rb
spec/controllers/service_providers_controller_spec.rb

[LG-10946](https://cm-jira.usa.gov/browse/LG-10946)
The `Api/ServiceProviderController#update` method was called by a user button press on the front end. This feels like not the best place for this method, this PR moves it to the `ServiceProviderController` and renames it to `publish` as the action is completes is re-publishing the SPs in the int environment.

Move Update action from API controller

---

app/views/users/index.html.erb

I noticed a small UX bug on the users/index view after the design update. 
Before:
After:

Add flex display to buttons

---

app/views/env/index.html.erb

I noticed earlier today that our environments dashboard is showing large icons after changes in the design system [[1](https://github.com/18F/identity-dashboard/pull/748), [2](https://github.com/18F/identity-dashboard/pull/750)].
https://dashboard.dev.identitysandbox.gov/env
**Before this PR**
**After this PR**
This PR resizes the icons on the dashboard page here: https://dashboard.dev.identitysandbox.gov/env.
Note: Searching for `image_tag` across this repo shows me other potential icon size problems in `app/views/service_providers/_service_provider_table_row.erb` and `app/views/users/index.html.erb`, but I can't easily get to those pages locally so I'm deferring that for now.
3. [x] Have you tagged the appropriate …

Resize Icons on Env Dashbord

---

app/javascript/packs/service_provider_form.js
app/views/service_providers/_form.html.erb
spec/features/service_providers_spec.rb

[LG-12748](https://cm-jira.usa.gov/browse/LG-12748)
[Slack Conversation](https://gsa-tts.slack.com/archives/C01SU3NB9T3/p1710941326342639)
Added `(*required)` designation on Assertion Consumer Service URL when partners use SAML auth protocol.  
We are already validating the input to ensure it's a URL string.

LG-12748 Require SAML ACSUrl

---

app/views/service_providers/_form.html.erb
app/views/service_providers/show.html.erb
config/locales/service_providers.en.yml

[Jira](https://cm-jira.usa.gov/browse/LG-11773)
[Slack](https://gsa-tts.slack.com/archives/C01SU3NB9T3/p1710880717210819)
Update Radio button toggle for Production/Sandbox to USWDS tiled radio group, update yes/no text for radios to Production/Sandbox;
Update Accessible radio button toggle to use USWDS tiled radio group, for consistency.
Areas tested/to test: Dashboard > Apps > Create a new app:
- Dashboard Configuration (formerly Production Configuration) section
- Accessible section
- Consider using [Conventional Comments](https://conventionalcomments.org/) to ensure that your feedback is clear …

LG-11773 new config toggle

---

app/views/service_providers/_form.html.erb
app/views/service_providers/show.html.erb
config/locales/service_providers.en.yml
package.json
spec/features/service_providers_spec.rb
yarn.lock

[LG-13064](https://cm-jira.usa.gov/browse/LG-13064)
[Slack Thread](https://gsa-tts.slack.com/archives/C04RGFTFD70/p1713212455936609)
* Use `t(string_html)` instead of `I18n.t(string_html)`, so that HTML is not escaped to text.
* Updated `span` classes from `text-heavy` to `text-bold`, which is already in our stylesheets and more legible.
* Updated tests to match appropriate text.
* Updated `caniuse-lite`.
- …

LG-13064 HTML parsing bug

---

app/controllers/service_providers_controller.rb
app/helpers/service_provider_helper.rb
app/views/service_providers/_form.html.erb
spec/helpers/service_provider_helper_spec.rb

https://gsa-tts.slack.com/archives/C01SU3NB9T3/p1715365675325969
* Adds a non-admin check to the initial conditional of the help_text editing check
* Updates the `help_text_empty?` method to handle when each help text key is an empty hash, and when it has translation values that are empty strings

Allow admins to edit integrations with empty help text
