.codeclimate.yml, .rubocop.yml, .scss-lint.yml, Gemfile, Gemfile.lock
**Why**: To ensure consistency in our code style and quality
=> Add Code Climate and linter configs

config/environments/production.rb
**Why**: We might not be deployed at cloud.gov
=> Add DEFAULT_URL_BASE env var production config

.rubocop.yml, spec/i18n_spec.rb
__Why__
Rubocop was throwing errors at the Capistrano DSL with my capify branch. We have
already configured this to work correctly on the IdP hence we'll copy that
config.
__How__
Copy the config from the IdP app.
=> Copy rubocop custom config from IdP

app/assets/stylesheets/components/_deploy.scss, app/assets/stylesheets/components/all.scss, app/controllers/home_controller.rb, app/services/deploy_status_checker.rb, app/views/home/_deploy.html.erb, app/views/home/index.html.slim, config/secrets.yml, spec/services/deploy_status_checker_spec.rb
**Why**:
So we can see what's going on
---
It probably needs tests or something
---
Here's a preview:
=> Add basic deploy dashboad to homepage

Capfile, Gemfile, Gemfile.lock, config/deploy.rb
**Why**:
We want passenger to restart after each deploy
cc @jgrevich 
see: https://github.com/18F/identity-idp/pull/538/files
=> Copy over passenger restart steps

app/services/deploy_status_checker.rb
**Why**: too much copy-pasta
I am very open to how we can make these config-based, like parse a JSON from an ENV key? Anybody have any suggestions? @pkarman @jgrevich @amoose ?
=> Fix hosts for demo env

app/services/deploy_status_checker.rb, app/views/home/_deploy.html.erb
**Why**: Adds useful information
=> Update Deploy Dashboard with links to apps and pending changes

app/controllers/users/service_providers_controller.rb, app/models/agency.rb, app/models/service_provider.rb, app/serializers/service_provider_serializer.rb, app/views/users/service_providers/_form.html.slim, app/views/users/service_providers/show.html.slim, db/migrate/20170117193214_add_agency_model.rb, db/migrate/20170117193703_move_agency_name.rb, db/schema.rb, spec/factories/agency.rb, spec/factories/service_providers.rb, spec/features/service_providers_spec.rb
Follow on to #46 -- please merge that first.
=> Convert Agency to model

.travis.yml, app/controllers/users/service_providers_controller.rb, app/models/service_provider.rb, app/serializers/service_provider_serializer.rb, app/views/users/service_providers/_form.html.slim, app/views/users/service_providers/show.html.slim, db/migrate/20170117222117_add_attribute_bundle.rb, db/schema.rb
**Why**: attribute_bundle determines which asserted attributes are returned in an Authentication request
=> Add ServiceProvider.attribute_bundle

app/services/deploy_status_checker.rb, spec/services/deploy_status_checker_spec.rb
=> Adds int to deploy status

Gemfile, Gemfile.lock, config/deploy.rb, config/deploy/int.rb, config/deploy/qa.rb
Fixes deployment for the latest permissions restrictions on our baseline image. 
Adds QA and INT stages for deployment
=> Fixes deployment

db/seeds.rb
Make it easier to deploy/run the app
Adds idempotent task to create initial agencies
=> Adds agency seeds

app/controllers/users/service_providers_controller.rb, app/serializers/service_provider_serializer.rb, app/views/users/service_providers/_form.html.slim, app/views/users/service_providers/show.html.slim, db/migrate/20170209190458_add_redirect_uri_to_service_providers.rb, db/schema.rb, spec/serializers/service_provider_serializer_spec.rb
**Why**: Support OpenID Connect self-serve
--
=> Add service_providers.redirect_uri

app/views/users/service_providers/_form.html.slim, spec/features/service_providers_spec.rb
Replaces multi select with checkboxes.
- Needs styling
=> Use checkboxes for attribute bundle

.env.test, app/services/service_provider_updater.rb, spec/support/fake_saml_idp.rb
**Why**: See https://github.com/18F/identity-idp/pull/1108
=> Send dashboard API token in headers when hitting IDP API

app/controllers/application_controller.rb, app/services/deploy_status_checker.rb, config/secrets.yml
**Why**: No longer needed since app is deployed behind nginx. See
https://github.com/18F/identity-dashboard/pull/70#discussion_r103475753
=> Remove HTTP auth config

Gemfile, Gemfile.lock, app/assets/javascripts/application.js, spec/support/capybara.rb
App was raising a missing jquery error
Added poltergeist config to raise jquery errors
=> Add jquery

app/assets/stylesheets/components/_alert.scss, app/controllers/organizations_controller.rb, app/models/organization.rb, app/policies/organization_policy.rb, app/views/organizations/_form.html.slim, app/views/organizations/edit.html.slim, app/views/organizations/index.html.slim, app/views/organizations/new.html.slim, app/views/organizations/show.html.slim, config/routes.rb, db/migrate/20170301184735_create_organizations.rb, db/schema.rb, spec/controllers/organization_spec.rb, spec/factories/organization.rb, spec/factories/users.rb, spec/features/organization_spec.rb, spec/models/organization_spec.rb
Only admins can CRUD organizations
Fixed notice image paths
=> Add CRUD for Organization model

app/models/service_provider.rb, app/views/service_providers/edit.html.slim, app/views/service_providers/new.html.slim, spec/models/service_provider_spec.rb
**Why**: Otherwise, there is no form validation but there is a postgres
error when submitting a form without agency selected
=> Add validation on service provider / agency relation

app/controllers/service_providers_controller.rb, app/models/organization.rb, app/models/service_provider.rb, app/views/service_providers/_form.html.slim, app/views/service_providers/show.html.slim, db/migrate/20170302011548_organization_has_many_service_providers.rb, db/schema.rb, spec/features/service_providers_spec.rb, spec/models/service_provider_spec.rb
=> Admin can add service provider to organization

Gemfile, Gemfile.lock
Hashie is surfacing an error 
This error is coming from an Omniauth depency. They are aware of the issue. 
Removing hashie from the gem file, updated gems
=> Update omniauth, omniauth-saml, and hashie

db/migrate/20170303182534_rename_organizations_to_user_groups.rb, db/schema.rb
* Enables devs with existing data to migrate
=> Add default value for `description` of empty string

app/models/user_group.rb, db/migrate/20170307195917_user_group_has_many_users.rb, db/schema.rb, spec/models/user_group_spec.rb
* set up connection in database and with rails
* next step is to add to form
=> User group has many users

.cfignore
* We are not using cloud foundry, no need to ignore things there
=> Remove cfignore file

.ruby-gemset
* We are using bundler, Gemset not needed. Haven't seen a gemset in the
wild in a few years :)
=> Remove gemset file

app/assets/javascripts/selectizer.js, app/assets/stylesheets/application.css.scss, app/controllers/user_groups_controller.rb, app/models/user.rb, app/models/user_group.rb, app/views/user_groups/_form.html.slim, app/views/user_groups/index.html.slim, spec/features/user_groups_spec.rb, spec/models/user_group_spec.rb
* This is just using simple_form's basic multiselect for now
* Select and press shift to select another
* We can do something fancier later?
=> Add multi-select input for adding users to user groups

spec/features/nav_links_spec.rb, spec/features/service_provider_approval_spec.rb, spec/features/service_providers_spec.rb, spec/features/user_groups_and_service_providers_spec.rb, spec/features/user_groups_spec.rb
**Why**: One feature per spec file
=> Reorganize feature spec files

app/assets/stylesheets/components/_table.scss, app/controllers/users_controller.rb, app/views/shared/_navigation_links.html.slim, app/views/user_groups/index.html.slim, app/views/users/index.html.slim, config/locales/en.yml, config/routes.rb, spec/features/nav_links_spec.rb, spec/features/users_spec.rb
Shows all users
Added 'Manage users' link to admin nav bar
=> Added users index page

app/controllers/users_controller.rb, app/policies/user_policy.rb, app/views/users/_form.html.slim, app/views/users/edit.html.slim, app/views/users/index.html.slim, config/locales/en.yml, config/routes.rb, spec/controllers/user_groups_controller_spec.rb, spec/controllers/users_controller_spec.rb, spec/features/users_spec.rb
- Added user access policy to limit edit feature to admins
=> Add ability to make user an admin

app/models/user.rb, app/views/service_providers/_form.html.slim, app/views/service_providers/edit.html.slim, app/views/service_providers/new.html.slim, spec/features/service_providers_spec.rb
Filters to users user group or nothing
New SP's default to users user group
Admin's can still select any user group
=> Added user group select for all users

Gemfile, Gemfile.lock
**Why**: Hakiri was complaining.
=> Update nokogiri to 1.7.1 for security patches

app/helpers/service_provider_helper.rb, app/views/service_providers/show.html.slim, spec/helpers/service_provider_helper_spec.rb
**Why:**   SVG's wont load from an external URL
Shows link to svg preview when svg is used
=> Show link when SVG logo is used

config/deploy/demo.rb
We no longer have a Demo env
Removes Demo from capistrano stages
=> Removes demo env from capistrano 

app/controllers/service_providers_controller.rb, app/controllers/user_groups_controller.rb, app/models/service_provider.rb, config/routes.rb, lib/tasks/dev.rake
Fixing issues being ignored by rubocop.
=> Automatically fixed by rubocop

config/environments/production.rb
This resolves https://github.com/18F/identity-private/issues/2558
=> Fix Uglifier ES6 error

db/seeds.rb
**Why:** We are a new agency integration and would like to properly integrate with INT.
=> Add USDS to seeds.db

app/assets/stylesheets/application.css.scss, app/models/group.rb, app/views/groups/_form.html.erb, spec/models/group_spec.rb
Removes model validation of description field and uses checkboxes when selecting users
=> Fixes to user groups

app/views/layouts/application.html.erb
The USWDS has an updated banner, see https://github.com/18F/identity-dev-docs/pull/61
=> Update banner with new content

app/controllers/service_providers_controller.rb, app/views/service_providers/all.html.erb
We need an easy way to see when a new application is added to the sandbox.
=> LG-822 Order applications and display a creation timestamp

.codeclimate.yml, .reek, .rubocop.yml, .scss-lint.yml, Gemfile, Gemfile.lock, Makefile
Uses the same code quality settings as the IdP
Updates configs for Code Climate, Rubocop, SCSS linter and reek
Thanks to Moncef for creating the initial PR: https://github.com/18F/identity-dashboard/pull/168
=> Updates code quality configuration

app/models/service_provider.rb, app/views/service_providers/_form.html.erb, spec/features/service_providers_spec.rb
Addresses these comments: 
https://github.com/18F/identity-dashboard/pull/215#pullrequestreview-263367624
=> LG-1452 Add new field to feature spec, add some copy

app/controllers/users_controller.rb, app/views/users/none.html.erb, spec/controllers/users_controller_spec.rb
Thanks @jmhooper for identifying the issue and this workaround. 
I've submitted a ticket with HubSpot to address how to use their forms with a CSP.
=> Overrides CSP for hubspot script

README.md, app/views/layouts/application.html.erb, lib/tasks/dev.rake
Consistency
Replaces 'Dashboard' with configured app_name
=> Updates layout and readme to use configured app name

Gemfile, Gemfile.lock, app/models/service_provider.rb, app/models/service_provider_certificate.rb, app/views/service_providers/_certificate_expiration.html.erb, app/views/service_providers/_certificate_expiration_td.html.erb, app/views/service_providers/all.html.erb, app/views/service_providers/index.html.erb, app/views/service_providers/show.html.erb, config/application.yml.example, lib/tasks/check_certificates.rake, spec/models/service_provider_certificate_spec.rb
Why: To make it easy for partners and admins to see when certificates will expire and to highlight certificates that have expired or will expire soon.
Admin view:
Rake view:
=> LG-1610: certificate validation

app/assets/stylesheets/application.css.scss.erb, app/views/groups/index.html.erb, app/views/service_providers/all.html.erb, app/views/service_providers/index.html.erb
Added a local class so content wraps within the tables and tables stay within the canvas for groups and all app views.
=> LG-2047: Added text wrap mixin for table cells

app/assets/stylesheets/application.css.scss.erb, app/views/groups/index.html.erb
Removing table wrap on list of users in groups view
=> Table wrap

config/initializers/secure_headers.rb
Amos discovered that he was unable to login to the dashboard: https://gsa-tts.slack.com/archives/C23LEJLMC/p1571846124055000?thread_ts=1571845925.054100&cid=C23LEJLMC
=> Add *.identitysandbox.gov to form-action in the CSP

yarn.lock
**Why**: To pick up the new colors in this version
=> Upgrade the design system to 2.2.0

app/views/groups/_form.html.erb, app/views/groups/show.html.erb, app/views/service_providers/_form.html.erb, app/views/service_providers/show.html.erb, config/locales/en.yml, spec/features/groups_spec.rb
Could someone take a look at this draft branch? I have a minor rails syntax error on a hint I'm adding to the group label.
=> language changes related to teams

app/controllers/home_controller.rb, spec/controllers/home_controller_spec.rb
Resolves LG-2604 by redirecting to the service providers path for the root path (when logged in).
=> [LG-2604] Redirects root route to SP path for logged in users

app/controllers/home_controller.rb, app/controllers/teams_controller.rb, app/views/teams/_teams_list.html.erb, app/views/teams/index.html.erb, app/views/teams/show.html.erb, spec/features/teams_spec.rb, yarn.lock
**Why**: So it looks nice and is responsive
=> Change the teams UI to use the card layout

app/assets/stylesheets/application.css.scss.erb, app/views/teams/_teams_list.html.erb, app/views/teams/edit.html.erb, spec/features/teams_spec.rb
**Why:**  Because the delete button doesn't belong on the teams list cards
=> LG-2762 move delete team button

Gemfile.lock
=> Bump JSON to v2.3.0

app/controllers/users_controller.rb, app/policies/user_policy.rb, app/views/users/_form.html.erb, app/views/users/edit.html.erb, app/views/users/index.html.erb, config/locales/en.yml, db/schema.rb, spec/controllers/users_controller_spec.rb
**Why:** We want to allow admins to delete users so that stale or unverified users can be removed.
=> LG-2880 Enable admins to delete users

Gemfile, Gemfile.lock, spec/spec_helper.rb, spec/support/capybara.rb
**Why**: So that the webdrivers gem can figure out what version of chromedriver to use instead of me
=> Add the webdrivers gem

app/views/service_providers/_form.html.erb, app/views/service_providers/show.html.erb
need to leave it on for testing in other deployed envs.
=> LG-2871: force logo upload disabled in `int`

Gemfile, Gemfile.lock, db/migrate/20200609184921_add_deleted_at_to_users.rb, db/migrate/20200611124017_remove_email_uuid_unique_indexes_from_users.rb, db/migrate/20200611125630_add_email_uuid_where_deleted_at_indexes_to_users.rb, db/schema.rb, yarn.lock
https://cm-jira.usa.gov/browse/LG-2897
Migration to prep users for soft-deletion
I'll make a separate PR for users' model/view/controller updates
=> Enable soft deletion of users

config/agencies.yml, db/seeds.rb
#why
We are adding all root agency names to the list for self service.
Corresponds with https://github.com/18F/identity-idp-config/pull/129
=> Update agency names

Gemfile, Gemfile.lock, app/services/agency_seeder.rb, db/seeds.rb, spec/services/agency_seeder_spec.rb
- Hopefully fixes #375
cc @jgrevich can you try this PR in your environment to make sure it works as expected?
=> Update how we seed agencies to get around id/name DB unique constraints

package.json, spec/models/user_spec.rb, yarn.lock
This test sometimes fails because the arrays have the same elements in a different order
=> Fix flaky test

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/application.rb, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb, spec/config/lograge_spec.rb, spec/controllers/application_controller_spec.rb
Matches what we have for the IDP
Doesn't add an `events.log` like we have in the IDP, I am not sure that's needed yet
=> Use lograge for structured logs (LG-4156)

config/environments/production.rb
- Remove log_tags
- Lower log_level to :info
- Remove log_formatter override
=> Update logging config

Gemfile.lock
Does what it says on the tin! https://github.com/minad/mimemagic/issues/98
=> updating mimemagic to 0.3.6 due to yanked version

spec/features/service_providers_spec.rb
Turned out to be a lot simpler than I thought 😄.
=> [LG-4450] Add cert upload to feature spec for SP creation

config/routes.rb, spec/routing/security_events_spec.rb
=> Fix security_events/all routing

app/forms/security_event_form.rb, app/services/idp_public_keys.rb, spec/controllers/api/security_events_controller_spec.rb, spec/forms/security_event_form_spec.rb, spec/services/idp_public_keys_spec.rb
#417 wasn't quite up to date when it was merged
=> Rubocop fixes

app/models/team.rb, app/models/user.rb, app/models/user_team.rb, spec/factories/user_team.rb, spec/models/team_spec.rb, spec/models/user_spec.rb, spec/models/user_team_spec.rb
Resolves LG-4224
Also add UserTeam factory and model specs for all three models
=> [LG-4224] Add PaperTrail versioning to Users, Teams, and UserTeams

config/application.yml.example
This commit restructures the application.yml.example file so it's format matches the other repositories. This change is the first step in migrating the dashboard to IdentityConfig and using Hostdata to manage configs here.
=> Cleanup the dashboard application.yml

config/agencies.yml
[Slack discussion](https://gsa-tts.slack.com/archives/C23LEJLMC/p1619027763047400)
=> [LG-4522] Remove USACE agency and add USSS

config/status_checks.yml, spec/support/deploy_status_checker_helper.rb
**Why**: So that people can find them
Related:
- https://github.com/18F/identity-oidc-sinatra/pull/92
- https://github.com/18F/identity-oidc-sinatra/pull/93
- https://github.com/18F/identity-saml-sinatra/pull/80
- https://github.com/18F/identity-saml-sinatra/pull/82
=> Add staging and production sample apps to env page

config/agencies.yml
Resolves LG-4680
Data sourced from https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States and we already had DC in there.
=> [LG-4680] Add state and local agencies

app/serializers/service_provider_serializer.rb, spec/serializers/service_provider_serializer_spec.rb
Resolves LG-4740
Whoops left this out of #453
=> [LG-4740] Actually send email_nameid_format_allowed to IdP

app/controllers/service_providers_controller.rb, spec/controllers/service_providers_controller_spec.rb
...and that's why you always add test coverage
=> Use correct method name, add test coverage

app/services/risc_destination_updater.rb
**Why**: IDP is adding a level of nesting
See: https://github.com/18F/identity-idp/pull/5181 (specifically the `detail` change)
=> Update RISC event path

app/controllers/service_providers_controller.rb, app/helpers/service_provider_helper.rb, app/serializers/service_provider_serializer.rb, app/views/service_providers/_form.html.erb, app/views/service_providers/show.html.erb, db/migrate/20210826155141_add_signed_response_message_request_to_service_provider.rb, db/schema.rb, spec/serializers/service_provider_serializer_spec.rb
https://cm-jira.usa.gov/browse/LG-4667
* Add the signed_response_message_request boolean to the Service Provider model
* Create DB migration
* Add Yes/No radio button to dashboard
* Update appropriate unit tests
=> Add Signed Response Message Request to Service Provider

app/controllers/service_providers_controller.rb, app/models/service_provider.rb, app/views/service_providers/_form.html.erb, app/views/service_providers/show.html.erb, db/migrate/20210915155526_add_app_name_to_sp.rb, db/schema.rb
Work Ticket: https://cm-jira.usa.gov/browse/LG-5016
Changes:
* Add app_name as attr to Service Provider model
* Add app_name to Dashboard views
* Create DB migration
* Update unit tests accordingly
=> [LG-5016] Add app name as a required field to Service Provider

spec/factories/service_providers.rb, spec/features/service_providers_spec.rb
https://cm-jira.usa.gov/browse/LG-5014
-   Just adding a test for the work completed [here](https://github.com/18F/identity-dashboard/pull/492)
=> [LG-5014] Assert that saml fields render when editing a saml service provider

app/helpers/service_provider_helper.rb
I did not make a bug.
-   I noticed that we do not have default_AAL in the yaml blob
- I will follow up with tests but I did want this to get kicked down the road with work interruption
=> adding default_AAL to yaml blob

app/models/service_provider.rb, app/views/service_providers/show.html.erb, spec/factories/service_providers.rb, spec/features/service_providers_spec.rb, spec/models/service_provider_spec.rb
https://cm-jira.usa.gov/browse/LG-5364
-  We only want to validate empty attribute bundles for SAML with IAL2
-  Hiding return_to_app_url on the show page for OIDC service providers
- Added more specific tests for validations
- Added more specific error messages
=>  [LG-5364] Adjustments to attribute validations

app/views/service_providers/show.html.erb
https://cm-jira.usa.gov/browse/LG-5017
-   Add missing styles to saml fields on service provider show page
=> Add missing styles to saml fields on service provider show page

app/views/env/index.html.erb, config/status_checks.yml, spec/support/deploy_status_checker_helper.rb
updated specs as required
https://cm-jira.usa.gov/browse/XX-XXXX
-   Add a description of your changes here
=> Added DM to idp dashboard

app/javascript/app/service-provider-form.js, app/models/service_provider.rb, spec/models/service_provider_spec.rb
https://cm-jira.usa.gov/browse/XX-XXXX
Added `all_emails` to attribute bundles. Validation handled.
=> Added missing attribute to bundle selection

app/controllers/service_providers_controller.rb, spec/controllers/service_providers_controller_spec.rb
https://cm-jira.usa.gov/browse/LG-5327
-   Adding controller method to clear leading and trailing whitespaces to user supplied data in the service provider form
=> [LG-5327] clear input formatting

app/controllers/service_providers_controller.rb
https://cm-jira.usa.gov/browse/LG-6691
-   removing whitespace from redirect_uris to help handle user errors more effectively
=> [LG-6691] removing whitespace from redirect uris

app/models/service_provider.rb, spec/models/service_provider_spec.rb
https://cm-jira.usa.gov/browse/LG-5982
-  does what it says on the tin
=> [LG-5982] Allow the target attribute in help text links

app/helpers/service_provider_helper.rb, spec/features/service_providers_spec.rb
https://cm-jira.usa.gov/browse/LG-6031
-  Bugfix
=> [LG-6031] Fix bug when rendering SPs without teams

app/models/service_provider.rb, spec/models/service_provider_spec.rb
=> Allow more complex HTML elements in SP help text

app/models/service_provider.rb, app/views/service_providers/_form.html.erb
-  Help text in support of #526 
=> Add info about permitted HTML tags for help text

pull_request_template.md
- Updates the PR Template to remove reference to JIRA and be more general so that any relevant links to Zendesk or Slack could be included.
- Updates the Checklist to match our workflow a bit closer.
- Also starts adding some PR Review conventions.
=> Update the pr template to match the new identity-idp-config template

app/javascript/packs/application.js, app/views/users/edit.html.erb
* https://gsa-tts.slack.com/archives/C01SU3NB9T3/p1657059261904399
* #559
Initializes `@rails/ujs` per [usage documentation](https://github.com/rails/rails/tree/main/actionview/app/assets/javascripts#usage) so that it applies the expected behavior.
Reverts `button_to` to `link_to` resolve [issues with nested form](https://stackoverflow.com/a/34644553).
1. Go to http://localhost:3001
2. Sign in with admin user
3. Go to Admin > Users
4. Edit a user
5. Click "Delete"
6. Observe confirmation prompt, confirming that UJS is initialized and applied to the `link_to` element
7. Click "Update"
8. Observe page submits, confirming fix to nested form submission bug
9. [x] Have you tagged the appropriate dev(s) for review?
10. [x] …
=> Initialize unobtrusive JavaScript, revert button_to

app/controllers/teams_controller.rb
Also fix bug where failed creation / updates would result in an empty dropdown
https://gsa-tts.slack.com/archives/C01SU3NB9T3/p1671121379728469
=> Order agency dropdown alphabetically

.circleci/config.yml
Problem: CircleCI keeps failing with
> Directory (...) you are trying to checkout to is not empty and not a git repository
So the solution was to check out the code first before installing browser tools
=> Fix "working directory not empty" issue in CircleCI

app/helpers/service_provider_helper.rb, app/views/service_providers/_service_provider_yaml.erb, spec/features/service_providers_spec.rb
[LG-6909](https://cm-jira.usa.gov/browse/LG-6909)
Added push_notification_url to the map_config_attributes function 
=> add push_notification_url

config/locales/en.yml
discovered during local testing
Fix typo
=> Fix typo in confirm remove user headline

Gemfile, Gemfile.lock
N/A
Newer version supports M1 macs, see 18f/identity-idp#7133
=> Update webdrivers gem

Gemfile, Gemfile.lock
The main reason for this was so we could no longer depend on `httparty` gem
Updates our forked `saml_idp`
=> Update saml_idp gem

app/helpers/service_provider_helper.rb, spec/features/service_providers_spec.rb, spec/helpers/service_provider_helper_spec.rb
[LG-9181](https://cm-jira.usa.gov/browse/LG-9181)
Cleaning up the existing YAML output in the dashboard for PSE's by removing quotation marks so there is no longer an issue of having to add them in places where they were previously missing. Also moving all URL's to the bottom so they are grouped together. 
=> Np/lg 9181/cleanup yaml

spec/services/service_provider_logo_updater_spec.rb
Tests were intermittently failing https://app.circleci.com/pipelines/github/18F/identity-dashboard/1292/workflows/2f4c96d4-e929-4681-a99d-b24684f6a66c/jobs/2251
A stub was too open, and creating all kinds of unrelated changes.
=> Make File.directory? stub more specific

app/controllers/api/service_providers_controller.rb, config/routes.rb, spec/controllers/api/service_providers_controller_spec.rb
https://cm-jira.usa.gov/browse/LG-9761
Add a show json response for individual service providers
=> Create show endpoint

app/serializers/service_provider_serializer.rb, spec/serializers/service_provider_serializer_spec.rb
https://cm-jira.usa.gov/browse/LG-9761
protocol key (just oidc/saml) is needed for the integration script.
=> update serializer to include protocol

app/serializers/service_provider_serializer.rb, spec/serializers/service_provider_serializer_spec.rb
https://cm-jira.usa.gov/browse/LG-9990
This change adds the pkce attribute to the individual service provider api response
=> LG-9990 Add pkce attribute

app/views/service_providers/new.html.erb, config/locales/en.yml
[LG-10221](https://cm-jira.usa.gov/browse/LG-10221)
Update language that said "Create test app" to just say "Create app" (several partners were confused and thought this was only for creating test applications) 
=> fix 'test app' labels

config/newrelic.yml
This PR disables New Relic so it does not run locally. Copied slightly from https://github.com/18F/identity-idp/blob/main/config/newrelic.yml
=> Disable NewRelic when not in production

lib/identity_config.rb
Brings in the ability to read configuration from system environment variables (copied from https://github.com/18F/identity-idp/pull/8452) to facilitate containerization of the dashboard application.
=> Add support for reading configuration from system environment variables

app/controllers/tools_controller.rb, spec/controllers/tools_controller_spec.rb
https://gsa-tts.slack.com/archives/C05E50XNN8Z/p1699375872725859?thread_ts=1699036588.857439&cid=C05E50XNN8Z
Small copy change
=> Update language to be clear

app/controllers/tools_controller.rb, config/oidc.yml, spec/controllers/tools_controller_spec.rb
Updates `stages/int` to update the dashboard to use the latest updates
=> Upgrade INT dashboard to use latest updates

config/newrelic.yml
Some [NewRelic fuzzing errors](https://one.newrelic.com/nr1-core/errors-inbox/entity-inbox/MTM3NjM3MHxBUE18QVBQTElDQVRJT058MTA0NDEwNTc2?account=1376370&begin=1701434729213&end=1701445529213&filters=%28domain%20IN%20%28%27APM%27%2C%20%27EXT%27%29%20AND%20type%20IN%20%28%27APPLICATION%27%2C%20%27SERVICE%27%29%29&state=aa5e206f-ee8b-7d94-c2c7-0a5b4646ccaf). More convo here: https://gsa-tts.slack.com/archives/C04RGFTFD70/p1701444949389339
Tells NewRelic to ignore fuzzing errors. 
- Consider using [Conventional Comments](https://conventionalcomments.org/) to ensure that your feedback is clear and …
=> Add ignored newrelic error classes

app/helpers/service_provider_helper.rb, app/models/service_provider.rb, spec/helpers/service_provider_helper_spec.rb, spec/models/service_provider_spec.rb
https://cm-jira.usa.gov/browse/LG-11216
This change:
* fixes a small UX bug introduced in https://github.com/18F/identity-dashboard/pull/701 
* deletes some unused code
* Adds a check to ensure that the file type of the uploaded logo matches the file extension
=> LG-11216 img warning

.gitlab-ci.yml
=> Add gitlab ci secret detection scans

app/controllers/service_providers_controller.rb
[LG-12042](https://cm-jira.usa.gov/browse/LG-12042) 
I forgot about the create app view - 1 line change
=> Add help text var to new view

app/views/service_providers/_service_provider_table_row.erb
[LG-12206](https://cm-jira.usa.gov/browse/LG-12206)
Add alt text to the icons in the active column on the app listing page.
=> Add alt text to (in)active icons on app lists

app/controllers/service_providers_controller.rb, app/helpers/service_provider_helper.rb, app/views/service_providers/_form.html.erb, app/views/service_providers/_service_provider_table.erb, app/views/service_providers/_service_provider_table_header.erb, app/views/service_providers/_service_provider_table_row.erb, app/views/service_providers/show.html.erb, config/locales/service_providers.en.yml, config/locales/simple_form.en.yml, spec/helpers/service_provider_helper_spec.rb
LG-12614 [Dashboard] Make "active" column more understandable
- remove col from production apps
- change Active label in apps list and create to Accessible
- include title text on Accessible column
=> LG-12614 change active column label

.circleci/config.yml
https://gsa-tts.slack.com/archives/C04RGFTFD70/p1710353790426709
Updating orbs: https://github.com/CircleCI-Public/browser-tools-orb/issues/108#issuecomment-1961800218
=> Updates circleci chrome-version bc chromedriver won't download

app/controllers/security_events_controller.rb, app/helpers/team_helper.rb, app/policies/security_event_policy.rb, app/policies/team_policy.rb, app/views/home/authenticated/index.html.erb, app/views/security_events/all.html.erb, app/views/security_events/index.html.erb, app/views/service_providers/_service_provider_yaml.erb, app/views/service_providers/show.html.erb, app/views/teams/users/_form.html.erb, spec/controllers/teams_controller_spec.rb, spec/factories/users.rb, spec/features/accessibility/emails_spec.rb, spec/features/accessibility/env_spec.rb, spec/features/accessibility/home_spec.rb, spec/features/accessibility/security_events_spec.rb, spec/features/accessibility/service_providers_spec.rb, spec/features/accessibility/teams_spec.rb, spec/features/accessibility/tools_spec.rb, spec/features/accessibility/users_spec.rb, spec/policies/security_event_policy_spec.rb, spec/policies/team_policy_spec.rb, spec/services/user_session_spec.rb
https://cm-jira.usa.gov/browse/LG-12904
This change backfills a bunch of accessibility tests for views that were previously untested.
The change includes:
- moving some authorization logic to the pundit Policy classes
- updating existing tests
- adding tests
- fixing accessibility and html validation errors
=> LG-12904 add axe tests

app/views/home/authenticated/index.html.erb, app/views/service_providers/_service_provider_table.erb, app/views/service_providers/new.html.erb, app/views/teams/_no_teams.html.erb, app/views/teams/index.html.erb, app/views/teams/new.html.erb, app/views/tools/saml_request.html.erb
[LG-12301](https://cm-jira.usa.gov/browse/LG-12301)
Add page descriptions per google doc 
https://docs.google.com/document/d/1nWUep38DnkBNbftmhNHxqv1p0rpW1mFDYID-3LDvlrw/edit
=> LG-12301 add page descriptions 
